echo customer=rcarrata > /var/tmp/envs-ocp4
echo PrivateHostedZone="asimov.lab" >> /var/tmp/envs-ocp4
echo VpcCidr="10.0.0.0/16" >> /var/tmp/envs-ocp4
echo Subnet0Cidr="10.0.0.0/24" >> /var/tmp/envs-ocp4
echo Subnet1Cidr="10.0.1.0/24" >> /var/tmp/envs-ocp4
echo Subnet2Cidr="10.0.2.0/24" >> /var/tmp/envs-ocp4
echo DNSServerIp="10.0.3.10" >> /var/tmp/envs-ocp4
echo SubnetPublicCidr="10.0.3.0/24" >> /var/tmp/envs-ocp4
echo AvailabilityZone0="eu-west-1a" >> /var/tmp/envs-ocp4
echo AvailabilityZone1="eu-west-1b" >> /var/tmp/envs-ocp4
echo AvailabilityZone2="eu-west-1c" >> /var/tmp/envs-ocp4
echo AWSKEY="TO_CHANGE" >> /var/tmp/envs-ocp4
echo AWSSECRETKEY="TO_CHANGE" >> /var/tmp/envs-ocp4
export REGION=eu-west-1
echo REGION=eu-west-1 >> /var/tmp/envs-ocp4
echo s3Endpoint="com.amazonaws.${REGION}.s3" >> /var/tmp/envs-ocp4
echo elbEndpoint="com.amazonaws.${REGION}.elasticloadbalancing" >> /var/tmp/envs-ocp4
echo ec2Endpoint="com.amazonaws.${REGION}.ec2" >> /var/tmp/envs-ocp4
echo LOGFILE=/var/tmp/aws-resources >> /var/tmp/envs-ocp4
echo OCP_RELEASE=4.9.11 >> /var/tmp/envs-ocp4
echo ARCHITECTURE=x86_64 >> /var/tmp/envs-ocp4
export IpProxy="bastion.${PrivateHostedZone}"
IpProxy="bastion.${PrivateHostedZone}" >> /var/tmp/envs-ocp4
